# Maps an app name to its sketchybar-app-font ligature.
# Generated from sketchybar-app-font v2.0.28 (install.sh pins the same version).
# Missing app? Add a line; icon names are listed in the font release notes.

icon_map() {
  case "$1" in
  "Live") echo ":ableton:" ;;
  "Adobe Bridge") echo ":adobe_bridge:" ;;
  "Affinity Designer") echo ":affinity_designer:" ;;
  "Affinity Designer 2") echo ":affinity_designer_2:" ;;
  "Affinity Photo") echo ":affinity_photo:" ;;
  "Affinity Photo 2") echo ":affinity_photo_2:" ;;
  "Affinity Publisher") echo ":affinity_publisher:" ;;
  "Affinity Publisher 2") echo ":affinity_publisher_2:" ;;
  "Airmail") echo ":airmail:" ;;
  "Alacritty") echo ":alacritty:" ;;
  "Alfred") echo ":alfred:" ;;
  "Android Messages") echo ":android_messages:" ;;
  "Android Studio") echo ":android_studio:" ;;
  "Anki") echo ":anki:" ;;
  "Anytype") echo ":anytype:" ;;
  "App Eraser") echo ":app_eraser:" ;;
  "App Store") echo ":app_store:" ;;
  "Arc") echo ":arc:" ;;
  "Arduino") echo ":arduino:" ;;
  "Arduino IDE") echo ":arduino:" ;;
  "Atom") echo ":atom:" ;;
  "Audacity") echo ":audacity:" ;;
  "Bambu Studio") echo ":bambu_studio:" ;;
  "MoneyMoney") echo ":bank:" ;;
  "Battle.net") echo ":battle_net:" ;;
  "Bear") echo ":bear:" ;;
  "BetterTouchTool") echo ":bettertouchtool:" ;;
  "Bilibili") echo ":bilibili:" ;;
  "哔哩哔哩") echo ":bilibili:" ;;
  "Bitwarden") echo ":bit_warden:" ;;
  "Blender") echo ":blender:" ;;
  "BluOS Controller") echo ":bluos_controller:" ;;
  "Calibre") echo ":book:" ;;
  "Brave Browser") echo ":brave_browser:" ;;
  "BusyCal") echo ":busycal:" ;;
  "Calculator") echo ":calculator:" ;;
  "Calculette") echo ":calculator:" ;;
  "Calendar") echo ":calendar:" ;;
  "日历") echo ":calendar:" ;;
  "Fantastical") echo ":calendar:" ;;
  "Cron") echo ":calendar:" ;;
  "Amie") echo ":calendar:" ;;
  "Calendrier") echo ":calendar:" ;;
  "Notion Calendar") echo ":calendar:" ;;
  "Caprine") echo ":caprine:" ;;
  "Amazon Chime") echo ":chime:" ;;
  "Citrix Workspace") echo ":citrix:" ;;
  "Citrix Viewer") echo ":citrix:" ;;
  "Claude") echo ":claude:" ;;
  "ClickUp") echo ":click_up:" ;;
  "Code") echo ":code:" ;;
  "Code - Insiders") echo ":code:" ;;
  "Cold Turkey Blocker") echo ":cold_turkey_blocker:" ;;
  "Color Picker") echo ":color_picker:" ;;
  "数码测色计") echo ":color_picker:" ;;
  "Copilot") echo ":copilot:" ;;
  "CotEditor") echo ":coteditor:" ;;
  "Creative Cloud") echo ":creative_cloud:" ;;
  "Cursor") echo ":cursor:" ;;
  "Cypress") echo ":cypress:" ;;
  "DataGrip") echo ":datagrip:" ;;
  "DataSpell") echo ":dataspell:" ;;
  "DaVinci Resolve") echo ":davinciresolve:" ;;
  "Deezer") echo ":deezer:" ;;
  "CleanMyMac X") echo ":desktop:" ;;
  "DEVONthink 3") echo ":devonthink3:" ;;
  "DingTalk") echo ":dingtalk:" ;;
  "钉钉") echo ":dingtalk:" ;;
  "阿里钉") echo ":dingtalk:" ;;
  "Discord") echo ":discord:" ;;
  "Discord Canary") echo ":discord:" ;;
  "Discord PTB") echo ":discord:" ;;
  "Docker") echo ":docker:" ;;
  "Docker Desktop") echo ":docker:" ;;
  "GrandTotal") echo ":dollar:" ;;
  "Receipts") echo ":dollar:" ;;
  "Double Commander") echo ":doublecmd:" ;;
  "Drafts") echo ":drafts:" ;;
  "draw.io") echo ":draw_io:" ;;
  "Dropbox") echo ":dropbox:" ;;
  "Element") echo ":element:" ;;
  "Emacs") echo ":emacs:" ;;
  "Evernote Legacy") echo ":evernote_legacy:" ;;
  "FaceTime") echo ":face_time:" ;;
  "FaceTime 通话") echo ":face_time:" ;;
  "Figma") echo ":figma:" ;;
  "Final Cut Pro") echo ":final_cut_pro:" ;;
  "Finder") echo ":finder:" ;;
  "访达") echo ":finder:" ;;
  "Firefox") echo ":firefox:" ;;
  "Firefox Developer Edition") echo ":firefox_developer_edition:" ;;
  "Firefox Nightly") echo ":firefox_developer_edition:" ;;
  "Folx") echo ":folx:" ;;
  "Fork") echo ":fork:" ;;
  "FreeTube") echo ":freetube:" ;;
  "Fusion") echo ":fusion:" ;;
  "System Preferences") echo ":gear:" ;;
  "System Settings") echo ":gear:" ;;
  "系统设置") echo ":gear:" ;;
  "Réglages Système") echo ":gear:" ;;
  "GitHub Desktop") echo ":git_hub:" ;;
  "Godot") echo ":godot:" ;;
  "GoLand") echo ":goland:" ;;
  "Chromium") echo ":google_chrome:" ;;
  "Google Chrome") echo ":google_chrome:" ;;
  "Google Chrome Canary") echo ":google_chrome:" ;;
  "Grammarly Editor") echo ":grammarly:" ;;
  "Home Assistant") echo ":home_assistant:" ;;
  "Hyper") echo ":hyper:" ;;
  "IntelliJ IDEA") echo ":idea:" ;;
  "IINA") echo ":iina:" ;;
  "Adobe Illustrator") echo ":illustrator:" ;;
  "Illustrator") echo ":illustrator:" ;;
  "Adobe InDesign") echo ":indesign:" ;;
  "InDesign") echo ":indesign:" ;;
  "Inkdrop") echo ":inkdrop:" ;;
  "Inkscape") echo ":inkscape:" ;;
  "Insomnia") echo ":insomnia:" ;;
  "Iris") echo ":iris:" ;;
  "iTerm") echo ":iterm:" ;;
  "iTerm2") echo ":iterm:" ;;
  "Jellyfin Media Player") echo ":jellyfin:" ;;
  "Joplin") echo ":joplin:" ;;
  "카카오톡") echo ":kakaotalk:" ;;
  "KakaoTalk") echo ":kakaotalk:" ;;
  "Kakoune") echo ":kakoune:" ;;
  "KeePassXC") echo ":kee_pass_x_c:" ;;
  "Keyboard Maestro") echo ":keyboard_maestro:" ;;
  "Keynote") echo ":keynote:" ;;
  "Keynote 讲演") echo ":keynote:" ;;
  "kitty") echo ":kitty:" ;;
  "League of Legends") echo ":league_of_legends:" ;;
  "LibreWolf") echo ":libre_wolf:" ;;
  "Adobe Lightroom") echo ":lightroom:" ;;
  "Lightroom Classic") echo ":lightroomclassic:" ;;
  "LINE") echo ":line:" ;;
  "Linear") echo ":linear:" ;;
  "LM Studio") echo ":lm_studio:" ;;
  "LocalSend") echo ":localsend:" ;;
  "Logic Pro") echo ":logicpro:" ;;
  "Logseq") echo ":logseq:" ;;
  "Canary Mail") echo ":mail:" ;;
  "HEY") echo ":mail:" ;;
  "Mail") echo ":mail:" ;;
  "Mailspring") echo ":mail:" ;;
  "MailMate") echo ":mail:" ;;
  "Superhuman") echo ":mail:" ;;
  "Spark") echo ":mail:" ;;
  "邮件") echo ":mail:" ;;
  "MAMP") echo ":mamp:" ;;
  "MAMP PRO") echo ":mamp:" ;;
  "Maps") echo ":maps:" ;;
  "Google Maps") echo ":maps:" ;;
  "Marta") echo ":marta:" ;;
  "Matlab") echo ":matlab:" ;;
  "Mattermost") echo ":mattermost:" ;;
  "Messages") echo ":messages:" ;;
  "信息") echo ":messages:" ;;
  "Nachrichten") echo ":messages:" ;;
  "Messenger") echo ":messenger:" ;;
  "Microsoft Edge") echo ":microsoft_edge:" ;;
  "Microsoft Excel") echo ":microsoft_excel:" ;;
  "Microsoft Outlook") echo ":microsoft_outlook:" ;;
  "Microsoft PowerPoint") echo ":microsoft_power_point:" ;;
  "Microsoft Remote Desktop") echo ":microsoft_remote_desktop:" ;;
  "Microsoft Teams") echo ":microsoft_teams:" ;;
  "Microsoft Teams (work or school)") echo ":microsoft_teams:" ;;
  "Microsoft Word") echo ":microsoft_word:" ;;
  "Min") echo ":min_browser:" ;;
  "Miro") echo ":miro:" ;;
  "MongoDB Compass") echo ":mongodb:" ;;
  "mpv") echo ":mpv:" ;;
  "Mullvad Browser") echo ":mullvad_browser:" ;;
  "Music") echo ":music:" ;;
  "音乐") echo ":music:" ;;
  "Musique") echo ":music:" ;;
  "Neovide") echo ":neovide:" ;;
  "neovide") echo ":neovide:" ;;
  "Neovim") echo ":neovim:" ;;
  "neovim") echo ":neovim:" ;;
  "nvim") echo ":neovim:" ;;
  "网易云音乐") echo ":netease_music:" ;;
  "Noodl") echo ":noodl:" ;;
  "Noodl Editor") echo ":noodl:" ;;
  "NordVPN") echo ":nord_vpn:" ;;
  "Notability") echo ":notability:" ;;
  "Notes") echo ":notes:" ;;
  "备忘录") echo ":notes:" ;;
  "Notion") echo ":notion:" ;;
  "Nova") echo ":nova:" ;;
  "Numbers") echo ":numbers:" ;;
  "Numbers 表格") echo ":numbers:" ;;
  "Obsidian") echo ":obsidian:" ;;
  "OBS") echo ":obsstudio:" ;;
  "OmniFocus") echo ":omni_focus:" ;;
  "1Password") echo ":one_password:" ;;
  "Open Video Downloader") echo ":open_video_downloader:" ;;
  "ChatGPT") echo ":openai:" ;;
  "OpenVPN Connect") echo ":openvpn_connect:" ;;
  "Opera") echo ":opera:" ;;
  "OrbStack") echo ":orbstack:" ;;
  "OrcaSlicer") echo ":orcaslicer:" ;;
  "Orion") echo ":orion:" ;;
  "Orion RC") echo ":orion:" ;;
  "Pages") echo ":pages:" ;;
  "Pages 文稿") echo ":pages:" ;;
  "Parallels Desktop") echo ":parallels:" ;;
  "Parsec") echo ":parsec:" ;;
  "Preview") echo ":pdf:" ;;
  "预览") echo ":pdf:" ;;
  "Skim") echo ":pdf:" ;;
  "zathura") echo ":pdf:" ;;
  "Aperçu") echo ":pdf:" ;;
  "PDF Expert") echo ":pdf_expert:" ;;
  "Pearcleaner") echo ":pearcleaner:" ;;
  "Phoenix Slides") echo ":phoenix_slides:" ;;
  "Adobe Photoshop") echo ":photoshop:" ;;
  "PhpStorm") echo ":php_storm:" ;;
  "Pi-hole Remote") echo ":pihole:" ;;
  "Pine") echo ":pine:" ;;
  "Plex") echo ":plex:" ;;
  "Plexamp") echo ":plexamp:" ;;
  "Podcasts") echo ":podcasts:" ;;
  "播客") echo ":podcasts:" ;;
  "PomoDone App") echo ":pomodone:" ;;
  "Postman") echo ":postman:" ;;
  "Proton Mail") echo ":proton_mail:" ;;
  "Proton Mail Bridge") echo ":proton_mail:" ;;
  "PrusaSlicer") echo ":prusaslicer:" ;;
  "SuperSlicer") echo ":prusaslicer:" ;;
  "PyCharm") echo ":pycharm:" ;;
  "QQ") echo ":qq:" ;;
  "QQ音乐") echo ":qqmusic:" ;;
  "QQMusic") echo ":qqmusic:" ;;
  "Quantumult X") echo ":quantumult_x:" ;;
  "qutebrowser") echo ":qute_browser:" ;;
  "Raindrop.io") echo ":raindrop_io:" ;;
  "Reeder") echo ":reeder5:" ;;
  "Reminders") echo ":reminders:" ;;
  "提醒事项") echo ":reminders:" ;;
  "Rappels") echo ":reminders:" ;;
  "Replit") echo ":replit:" ;;
  "Rider") echo ":rider:" ;;
  "JetBrains Rider") echo ":rider:" ;;
  "Rio") echo ":rio:" ;;
  "Royal TSX") echo ":royaltsx:" ;;
  "Safari") echo ":safari:" ;;
  "Safari浏览器") echo ":safari:" ;;
  "Safari Technology Preview") echo ":safari:" ;;
  "Sequel Ace") echo ":sequel_ace:" ;;
  "Sequel Pro") echo ":sequel_pro:" ;;
  "Setapp") echo ":setapp:" ;;
  "SF Symbols") echo ":sf_symbols:" ;;
  "Signal") echo ":signal:" ;;
  "sioyek") echo ":sioyek:" ;;
  "Sketch") echo ":sketch:" ;;
  "Skype") echo ":skype:" ;;
  "Slack") echo ":slack:" ;;
  "Spark Desktop") echo ":spark:" ;;
  "Spotify") echo ":spotify:" ;;
  "Spotlight") echo ":spotlight:" ;;
  "Sublime Text") echo ":sublime_text:" ;;
  "superProductivity") echo ":superproductivity:" ;;
  "Tana") echo ":tana:" ;;
  "TeamSpeak 3") echo ":team_speak:" ;;
  "Telegram") echo ":telegram:" ;;
  "Terminal") echo ":terminal:" ;;
  "终端") echo ":terminal:" ;;
  "Typora") echo ":text:" ;;
  "Microsoft To Do") echo ":things:" ;;
  "Things") echo ":things:" ;;
  "Thunderbird") echo ":thunderbird:" ;;
  "TickTick") echo ":tick_tick:" ;;
  "TIDAL") echo ":tidal:" ;;
  "Tiny RDM") echo ":tinyrdm:" ;;
  "Todoist") echo ":todoist:" ;;
  "Toggl Track") echo ":toggl_track:" ;;
  "Tor Browser") echo ":tor_browser:" ;;
  "Tower") echo ":tower:" ;;
  "Transmit") echo ":transmit:" ;;
  "Trello") echo ":trello:" ;;
  "Tweetbot") echo ":twitter:" ;;
  "Twitter") echo ":twitter:" ;;
  "UTM") echo ":utm:" ;;
  "MacVim") echo ":vim:" ;;
  "Vim") echo ":vim:" ;;
  "VimR") echo ":vim:" ;;
  "Vivaldi") echo ":vivaldi:" ;;
  "VLC") echo ":vlc:" ;;
  "VMware Fusion") echo ":vmware_fusion:" ;;
  "VSCodium") echo ":vscodium:" ;;
  "Warp") echo ":warp:" ;;
  "WebStorm") echo ":web_storm:" ;;
  "微信") echo ":wechat:" ;;
  "WeChat") echo ":wechat:" ;;
  "企业微信") echo ":wecom:" ;;
  "WeCom") echo ":wecom:" ;;
  "WezTerm") echo ":wezterm:" ;;
  "WhatsApp") echo ":whats_app:" ;;
  "‎WhatsApp") echo ":whats_app:" ;;
  "Xcode") echo ":xcode:" ;;
  "Yandex Music") echo ":yandex_music:" ;;
  "Yuque") echo ":yuque:" ;;
  "语雀") echo ":yuque:" ;;
  "Zed") echo ":zed:" ;;
  "Zen Browser") echo ":zen_browser:" ;;
  "Zeplin") echo ":zeplin:" ;;
  "zoom.us") echo ":zoom:" ;;
  "Zotero") echo ":zotero:" ;;
  "Zulip") echo ":zulip:" ;;
  *) echo ":default:" ;;
  esac
}
